### PR TITLE
Feature/rewrite forked repo imports

### PR DESCRIPTION
**Pull request by msawangwan**
added a command that also can take sub-commands. please let me know if you want me to change it to simply, a single command. i just think it's cool that the command `fork` could possibly be augmented by a sub-command, in this case the sub-command `rewrite`.

also.. the package, `mod_test` is not so much a testing package but is more a tool. it actually makes more sense to change it to use `go generate` but i have to experiment with it more.

look forward to your review (and any questions ..).

thanks.

### CODE REVIEW

**Comment by msawangwan** [comment]
@marwan-at-work so although this re-writes the imports no problem.. i ran into another issue... 

again using `jwt-go` as the example:

i ran `mod fork rewrite` and `mod upgrade` to get the imports pointing to the correct repo (my fork) and version (`/v3`) -- ok, all is good.

i then import the fancy new `jwt-go` module into another project which is also a go module and run `go build`. now here the issue arises that `go get` (or whatever mechanism) continues to pull down and include the `+incompatible` requirement.

so what gives?

well, it's simple really and that is that `/v3` for `jwt-go` points to the release `v3.2.0`.. which is pinned to ...idk, i'm guessing here.. a commit? seriously, i don't know... anyway... the only solution i could come up with then was to just run `git tag -a v4.0.0` (since this would be a breaking change?) and then a `git push origin v4.0.0`, creating the proper release.

once i did that, running `go build` in the module importing the `jwt-go` fork worked like a charm. 

adding these 2 git commands into my PR would be trivial, given that you already have a lot of them in `migrate.go`, etc. the only issue here is that i know `jwt-go` is planning on an official `v4.0.0` so things might get messy but it's 1am right now and i'm not thinking all that clearly.

thoughts? am i missing something obvious.. ?

**Comment by msawangwan** [comment]
@marwan-at-work is this PR even necessary anymore? i can fix the conflicts or make any edits if you want me to.

**Comment by marwan-at-work** [comment]
@msawangwan what was this PR meant to do exactly? I haven't looked at it since you said it was still a work in progress. But in either cases, I'm happy with whatever decision you take :)

**Comment by marwan-at-work** [comment]
closing as stale, but feel free to re open :)

**Pull request closed without merging**
